-- 1. Create Users Table
create table public.users
(
    id           bigint generated by default as identity primary key,
    created_at   timestamp(6),
    email        varchar(100) not null constraint uk_users_email unique,
    enabled      boolean      not null,
    password     varchar(255) not null,
    phone_number varchar(20),
    role         varchar(255) not null check ((role)::text = ANY ((ARRAY ['ADMIN', 'DIRECTOR', 'MANAGER', 'CLIENT'])::text[])),
    username     varchar(50)  not null constraint uk_users_username unique
);

-- 2. Create Projects Table
create table public.projects (
     id           bigint generated by default as identity primary key,
     active       boolean      not null,
     created_date timestamp(6) not null,
     description  varchar(1000),
     name         varchar(100) not null constraint uk_projects_name unique
);

-- 3. Create Transactions Table
create table public.transactions
(
    id             bigint generated by default as identity primary key,
    amount         numeric(19, 2) not null,
    category       varchar(250)    not null, -- Removed long check constraint for brevity, usually fine to keep
    date           timestamp(6)   not null,
    description    varchar(1000)  not null,
    item_image_url varchar(255),
    payment_method varchar(30)    not null,
    receipt_url    varchar(255),
    type           varchar(20)    not null,
    project_id     bigint         not null constraint fk_transactions_project references public.projects,
    user_id        bigint         not null constraint fk_transactions_user references public.users
);