-- 1. USERS
CREATE TABLE public.users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6),
    email        VARCHAR(100) NOT NULL CONSTRAINT uk_users_email UNIQUE,
    enabled      BOOLEAN      NOT NULL,
    password     VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    role         VARCHAR(255) NOT NULL CHECK ((role)::text = ANY ((ARRAY ['ADMIN', 'DIRECTOR', 'MANAGER', 'INSTALLER', 'GUEST'])::text[])),
    username     VARCHAR(50)  NOT NULL CONSTRAINT uk_users_username UNIQUE,
    photo_url    VARCHAR(255),
    telegram_id  VARCHAR(50)
);

-- 2. COMPANIES
CREATE TABLE public.companies (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(100) NOT NULL,
                                  website VARCHAR(255),
                                  main_phone VARCHAR(50),
                                  email VARCHAR(100),
                                  notes VARCHAR(1000),
                                  active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 3. CONTACTS
CREATE TABLE public.contacts (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 company_id BIGINT CONSTRAINT fk_contacts_company REFERENCES public.companies(id) ON DELETE SET NULL,
                                 name VARCHAR(100) NOT NULL,
                                 role VARCHAR(50) NOT NULL,
                                 phone VARCHAR(50),
                                 email VARCHAR(100),
                                 notes VARCHAR(1000),
                                 active BOOLEAN NOT NULL DEFAULT TRUE,
                                 last_contact_date TIMESTAMP(6)
);

-- 4. COMPANY DOCUMENTS
CREATE TABLE public.company_documents (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          company_id BIGINT NOT NULL CONSTRAINT fk_company_documents_company REFERENCES public.companies(id),
                                          file_url VARCHAR(255) NOT NULL,
                                          file_type VARCHAR(50),
                                          uploaded_at TIMESTAMP(6) NOT NULL
);

-- 5. PROJECTS
CREATE TABLE public.projects (
                                 id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 active       BOOLEAN      NOT NULL,
                                 created_date TIMESTAMP(6) NOT NULL,
                                 finish_date  TIMESTAMP,
                                 description  VARCHAR(1000),
                                 name         VARCHAR(100) NOT NULL CONSTRAINT uk_projects_name UNIQUE,
                                 client_id    BIGINT CONSTRAINT fk_projects_client REFERENCES public.contacts(id),
                                 installer_id BIGINT CONSTRAINT fk_projects_installer REFERENCES public.contacts(id),
                                 equipment_dealer_id BIGINT CONSTRAINT fk_projects_equipment_dealer REFERENCES public.companies(id),
                                 address_text VARCHAR(255),
                                 latitude DOUBLE PRECISION,
                                 longitude DOUBLE PRECISION
);

-- 6. PROJECT MEDIA (Gallery)
CREATE TABLE public.project_media (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      project_id BIGINT NOT NULL CONSTRAINT fk_project_media_project REFERENCES public.projects(id) ON DELETE CASCADE,
                                      file_url VARCHAR(255) NOT NULL,
                                      file_type VARCHAR(50),
                                      description VARCHAR(1000),
                                      uploaded_at TIMESTAMP(6) NOT NULL
);

-- 7. EQUIPMENT
CREATE TABLE public.equipment (
                                  id BIGSERIAL PRIMARY KEY,
                                  project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
                                  name VARCHAR(255) NOT NULL,
                                  serial_number VARCHAR(255),
                                  warranty_months INT,
                                  notes TEXT
);

-- 8. PROJECT ADDITIONAL CONTACTS (Many-to-Many)
CREATE TABLE public.project_additional_contacts (
                                                    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
                                                    contact_id BIGINT REFERENCES public.contacts(id) ON DELETE CASCADE,
                                                    PRIMARY KEY (project_id, contact_id)
);

-- 9. TRANSACTIONS
CREATE TABLE public.transactions (
                                     id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     amount         NUMERIC(19, 2) NOT NULL,
                                     category       VARCHAR(250)   NOT NULL,
                                     date           TIMESTAMP(6)   NOT NULL,
                                     description    VARCHAR(1000)  NOT NULL,
                                     item_image_url VARCHAR(255),
                                     payment_method VARCHAR(30)    NOT NULL,
                                     receipt_url    VARCHAR(255),
                                     type           VARCHAR(20)    NOT NULL,
                                     project_id     BIGINT         NOT NULL CONSTRAINT fk_transactions_project REFERENCES public.projects(id),
                                     user_id        BIGINT         NOT NULL CONSTRAINT fk_transactions_user REFERENCES public.users(id)
);