-- 1. Add new columns to Users
ALTER TABLE users ADD COLUMN photo_url VARCHAR(255);
ALTER TABLE users ADD COLUMN telegram_id VARCHAR(50);

-- 2. Create the Project Gallery Table
CREATE TABLE project_media (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               project_id BIGINT NOT NULL CONSTRAINT fk_project_media_project REFERENCES projects(id),
                               file_url VARCHAR(255) NOT NULL,
                               file_type VARCHAR(50), -- To distinguish between 'IMAGE' or 'VIDEO'
                               uploaded_at TIMESTAMP(6) NOT NULL
);