-- 1. Create Companies Table
CREATE TABLE companies (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(100) NOT NULL,
                           website VARCHAR(255),
                           main_phone VARCHAR(50),
                           email VARCHAR(100),
                           notes VARCHAR(1000),
                           active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Create Contacts Table
CREATE TABLE contacts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          company_id BIGINT CONSTRAINT fk_contacts_company REFERENCES companies(id),
                          name VARCHAR(100) NOT NULL,
                          role VARCHAR(50) NOT NULL,
                          phone VARCHAR(50),
                          email VARCHAR(100),
                          notes VARCHAR(1000),
                          active BOOLEAN NOT NULL DEFAULT TRUE,
                          last_contact_date TIMESTAMP(6)
);

CREATE TABLE company_documents (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   company_id BIGINT NOT NULL CONSTRAINT fk_company_documents_company REFERENCES companies(id),
                                   file_url VARCHAR(255) NOT NULL,
                                   file_type VARCHAR(50),
                                   uploaded_at TIMESTAMP(6) NOT NULL
);